### ISSUE TITLE
undefined method `each' for nil:NilClass (NoMethodError)のErrorが発生する

### ISSUE THREAD

**Issue by AOESK01** [dugabot0/duga_bot#1]
Terminalから

ruby duga_bot.rb 
Follow this URL to have a user authorize your app: https://api.twitter.com/oauth/authenticate?oauth_token=xxxx
Enter PIN:

を実行した際、

Traceback (most recent call last):
	2: from duga_bot.rb:64:in `<main>'
	1: from duga_bot.rb:64:in `loop'
duga_bot.rb:75:in `block in <main>': undefined method `each' for nil:NilClass (NoMethodError)
Follow: command not found
Enter: command not found

のエラーが出ますが、何か足りていませんでしょうか？

**Comment by dugabot0** [comment]
duga_util.rbで参照されているDUGA_APPIDとDUGA_AGENTIDの環境変数が正しく設定されていますでしょうか？どちらもduga.jpで取得できます。
``` 
    params.store('appid', ENV['DUGA_APPID'])
    params.store('agentid', ENV['DUGA_AGENTID'])
```
ターミナルで確認してみてください。
```
echo $DUGA_APPID
echo $DUGA_AGENTID
```
正しく設定されていないと、
```
irb
> load 'duga_util.rb'
> DugaUtil.search_title({})
=> {"error"=>{"reason"=>"invalid applicationid"}}
```
などと返ってきてしまいます。問題なければ検索結果が出力されます。問題なく検索結果で出るようでしたら、`ruby duga_bot.rb`も問題なく動作すると思います。

それでもダメな場合は、
https://duga.jp/aff/member/webservice/
のAPIテストを試してみてください。

**Comment by AOESK01** [comment]
早速のご回答ありがとうございます。

当方、環境変数を使わずにそのままキーを当てはめておりましたが、EMV["キー"]としていたところを、EMV[]を取り除く形で指定したところ、PIN入力まで来ました。
ただ、PIN入力後に以下のエラーが発生しました。

Traceback (most recent call last):
duga_bot.rb:100:in `<main>': undefined local variable or method `response' for main:Object (NameError)
Did you mean?  respond_to?

APIテストを実施した結果、問題なく取得できていることが確認できました。

#<OAuth::AccessToken:0x000055ac922b2f70>
と出ているので、認証はできているような気がしています。

お手数をおかけしますが、ご確認よろしくお願いいたします。

**Comment by AOESK01** [comment]
logも確認しました、タイトル等が取得できていることを確認しました。
tmpの認証情報は何も情報がなく、空ファイルとなっておりました。

**Comment by dugabot0** [comment]
tmpの認証情報が空ファイルということはtwitter API keyが正しく設定できていないかもしれません。

おそらくtwitter APIからの返り値が201でないと思われます。logのこの返り値が出ているかと思いますが、確認していただけますか？また、以下のコードにバグがあったので、
a3bfc5c6dabaa5d1f2f3763846a94affe7f6d44a
で修正しました。こちらも試してみてください。twitter APIからのエラーメッセージが出るかと思います。
```
if res.code.to_i != 201
  log.error("#{JSON.pretty_generate(JSON.parse(res.body))}")  # response --> res
end
```

**Comment by AOESK01** [comment]
I, [2023-01-29T00:57:14.710741 #4153]  INFO -- : 403
E, [2023-01-29T00:57:14.748538 #4153] ERROR -- : {
  "title": "Forbidden",
  "status": 403,
  "detail": "Your client app is not configured with the appropriate oauth1 app permissions for this endpoint.",
  "type": "https://api.twitter.com/2/problems/oauth1-permissions"
}

TwitterDeveloperの設定がReadWriteになっていないような感じでしょうか・・・？

新しいコードを試したところ、実行時エラーは無くなりました。

**Comment by dugabot0** [comment]
そうですね、おそらくtwitter developerで、API keyの設定がread onlyになっているかもしれません。であれば、read/writeにしてもう一度試してみてください。

read/writeに設定したら、`tmp/access_token`を一度削除して、もう一度PIN入力をしないといけないかもしれません。こちらも試してみてください。

**Comment by AOESK01** [comment]
read onlyになっておりました、read/writeにしたところ、ツイートされることを確認しました。

ただ、tmp/access_tokenを削除後に行いましたが、access_tokenの内容が空のままになってしまい、逐一認証を求められてしまう状況にあります。

こちらは原因等お判りでしょうか？

**Comment by dugabot0** [comment]
すみません、バグがありました。
60224721c1744620dc5ba8047078d321042a052a
で修正しましたので、もう一度試していただけないでしょうか。1回目で`tmp/access_token`が書き込まれ、2回目からはPINを入力しなくてもよくなっているはずです。

**Comment by AOESK01** [comment]
早速のご対応ありがとうございます。
認証が求められなくなりました。ありがとうございます。

1点確認させていただきたいのですが、cronへの登録は、
「crontab -e」を入力して、nano等で編集し、「0 * * * * cd ~/duga_bot; ruby duga_bot.rb 」を追記する。
でよろしいでしょうか？

よろしくお願いいたします。

**Comment by dugabot0** [comment]
そうですね、
「0 * * * * cd ~/duga_bot; ruby duga_bot.rb 」
であれば、毎時0分に`cd ~/duga_bot; ruby duga_bot.rb`が実行されます。

**Comment by AOESK01** [comment]
ありがとうございます。

追記したものの、毎時0分にツイートが行われませんでした。
cron回りについて調べてみます。

**Comment by dugabot0** [comment]
cronのパスを`crontab -e`で設定しないといけないかもしれません。
https://qiita.com/positrium/items/a2de9af6c5b4d06b504e

**Comment by AOESK01** [comment]
cronのパスを設定したところ、無事にツイートされるようになりました、ありがとうございました！
